(setq scroll-step 1)
(setq next-screen-context-lines 1)
(setq line-number-mode t)
(setq column-number-mode t)
(setq mouse-yank-at-point t)
(setq user-mail-address "bv@bnl.gov")
(global-font-lock-mode 1)
